export interface Movie {
    year: string,
    genres: string[],
    ratings: number[],
    poster: string,
    contentRating: string,
    duration: string,
    releaseDate: string,
    averageRating: 0,
    storyline: string,
    actors: string[],
    imdbRating: number,
    posterurl: string,
    id: number,
    title: string,
}